# Generated by Django 5.2.7 on 2025-11-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='profile-pic/')),
                ('profession', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('Adress', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=400)),
                ('about_me', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_title', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('starting_year', models.DateField()),
                ('ending_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('starting_year', models.DateField()),
                ('ending_year', models.DateField()),
                ('about', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
